version: '3.2'
services:
  database:
    image: mysql:5.7
    ports:
      - "4306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=gtp3eAE4CzMcxnYNXTRh
